version: '2.3'

services:
  clickhouse1: 
    image: clickhouse/clickhouse-server:24.6
    init: true
    ports:
      - "8123:8123"
      - "8443:8443"
      - "9440:9440"
      - "9000:9000"
      - "9019:9019"
      - "9100:9100"
    volumes:
      - "./config.d:/etc/clickhouse-server/config.d"
      - "./ssl_client.xml:/etc/clickhouse-client/config.xml"
      - "./missing-ca-chain-certs/clickhouse1.key:/etc/clickhouse-server/certs/server.key"
      - "./missing-ca-chain-certs/clickhouse1.crt:/etc/clickhouse-server/certs/server.crt"
      # - "./missing-ca-chain-certs/ca_chain.crt:/ca_chain.crt"
      - "./missing-ca-chain-certs/missing_ca_chain.crt:/ca_chain.crt"
      - "./logs/clickhouse1:/var/log/clickhouse-server"
      
  clickhouse2: 
    image: clickhouse/clickhouse-server:24.6
    init: true
    volumes:
      - "./config.d:/etc/clickhouse-server/config.d"
      - "./ssl_client.xml:/etc/clickhouse-client/config.xml"
      - "./missing-ca-chain-certs/clickhouse2.crt:/etc/clickhouse-server/certs/server.crt"
      - "./missing-ca-chain-certs/clickhouse2.key:/etc/clickhouse-server/certs/server.key"
      - "./missing-ca-chain-certs/ca_chain.crt:/ca_chain.crt"
      - "./logs/clickhouse2:/var/log/clickhouse-server"


